# For the model only
MINUTES_OF_DATA_TO_LOOK_AT_FOR_MODEL = 840
ROLLING_AVERAGE_SIZE_FOR_MODEL = 10

# For general use
SAMPLES_OF_DATA_TO_LOOK_AT = 840

# For dataset creation
EXTENDED_SAMPLES_OF_DATA_TO_LOOK_AT = 10
ROLLING_AVERAGE_SIZE = 15
SAMPLES_TO_CONSIDER_FOR_PRE_PUMP = 10

# Sub-minute data gathering
SAMPLES_PER_MINUTE = 10
SECONDS_BETWEEN_SAMPLES = 6

# For running the actual program
TEST_MODE = False

# How many times we try a Binance API call if it fails
BINANCE_DATA_FETCH_ATTEMPT_AMOUNT = 5

# Old
GROUPED_DATA_SIZE = 5
BIN_SIZE_FOR_BINNING = 10
