MINUTES_OF_DATA_TO_LOOK_AT = 300
SAMPLES_OF_DATA_TO_LOOK_AT = 900
SAMPLES_PER_MINUTE = 3
GROUPED_DATA_SIZE = 5
# MINUTES_OF_DATA_TO_LOOK_AT = 75
TEST_MODE = True
ROLLING_AVERAGE_SIZE = 10
BIN_SIZE_FOR_BINNING = 10
